import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import Navbar from "./Navbar";
// import SaveUserOnLogin from "./SaveUserOnLogin";
import { ReduxProvider } from './redux/providers';
import Script from "next/script";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "BookWorm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic signUpFallbackRedirectUrl="/preferences">
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SaveUserOnLogin /> */}
        <ReduxProvider>
          <Navbar />
          {children}
      </ReduxProvider>
      <Script src="https://widget.cxgenie.ai/widget.js" data-aid="4a1b0274-a4da-4290-8686-caf8b2c395db" data-lang="en"></Script>
      </body>
    </html>
    </ClerkProvider>

  );
}
